---
- name: check mysql repository
  command: ls -l /etc/yum.repos.d/mysql-community.repo
  ignore_errors: true
  register: chkMySQLRepo
  tags:
    - mysql

- name: Install mysql repository
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present
  when: chkMySQLRepo|failed
  tags:
    - mysql

- name: install mysql5.6 client
  yum: name=mysql-community-client state=present enablerepo=mysql56-community*
  tags:
    - mysql